int getMaximumCount(char* string);
char* removeDuplicates(char* string);
void printDuplicates(char* string);
char* maskString(char* string1, char* string2);
void printReverseRecursively(char* string);
void permute(char* string, int start, int end);
static void swap(char* a, char* b);
void divideToNParts(char* string, int n);
int firstNonRepeatingCharacter(char* string);
void printWords(char* list[], char* word, int listSize);
void printSentenceReverse( char* string );
char* runLengthEncode(char* string);
int naivePatternSearch(char* string, char* pattern);
void reverse(char* string);
void removeDuplicatesWithoutAdditionalSpace(char* string);
void replaceSpace(char* string);
